# Generated by Django 4.2.6 on 2023-11-23 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
    ]
